#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
my $pwd = "$FindBin::Bin";

if ( $^O eq 'MSWin32' ) {
    exec( 'perl', "$pwd/bin/ignite", @ARGV );
} else {
    exec( "$pwd/bin/ignite", @ARGV );
}

